In [1]:
import pandas as pd
df_train = pd.read_csv('train.csv')
df_train.head(20)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
5,0005_01,Earth,False,F/0/P,PSO J318.5-22,44.0,False,0.0,483.0,0.0,291.0,0.0,Sandie Hinetthews,True
6,0006_01,Earth,False,F/2/S,TRAPPIST-1e,26.0,False,42.0,1539.0,3.0,0.0,0.0,Billex Jacostaffey,True
7,0006_02,Earth,True,G/0/S,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,NaN,Candra Jacostaffey,True
8,0007_01,Earth,False,F/3/S,TRAPPIST-1e,35.0,False,0.0,785.0,17.0,216.0,0.0,Andona Beston,True
9,0008_01,Europa,True,B/1/P,55 Cancri e,14.0,False,0.0,0.0,0.0,0.0,0.0,Erraiam Flatic,True
10,0008_02,Europa,True,B/1/P,TRAPPIST-1e,34.0,False,0.0,0.0,NaN,0.0,0.0,Altardr Flatic,True
11,0008_03,Europa,False,B/1/P,55 Cancri e,45.0,False,39.0,7295.0,589.0,110.0,124.0,Wezena Flatic,True
12,0009_01,Mars,False,F/1/P,TRAPPIST-1e,32.0,False,73.0,0.0,1123.0,0.0,113.0,Berers Barne,True
13,0010_01,Earth,False,G/1/S,TRAPPIST-1e,48.0,False,719.0,1.0,65.0,0.0,24.0,Reney Baketton,False
14,0011_01,Earth,False,F/2/P,TRAPPIST-1e,28.0,False,8.0,974.0,12.0,2.0,7.0,Elle Bertsontry,True
15,0012_01,Earth,False,NaN,TRAPPIST-1e,31.0,False,32.0,0.0,876.0,0.0,0.0,Justie Pooles,False
16,0014_01,Mars,False,F/3/P,55 Cancri e,27.0,False,1286.0,122.0,NaN,0.0,0.0,Flats Eccle,False
17,0015_01,Earth,False,F/4/P,55 Cancri e,24.0,False,0.0,1.0,0.0,0.0,637.0,Carry Hughriend,False
18,0016_01,Mars,True,F/5/P,TRAPPIST-1e,45.0,False,0.0,0.0,0.0,0.0,0.0,Alus Upead,True
19,0017_01,Earth,False,G/0/P,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,Lyde Brighttt,True

In [2]:
for el in df_train:
    print(el, df_train[el].unique())

PassengerId ['0001_01' '0002_01' '0003_01' ... '9279_01' '9280_01' '9280_02']
HomePlanet ['Europa' 'Earth' 'Mars' nan]
CryoSleep [False True nan]
Cabin ['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
Destination ['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
Age [39. 24. 58. 33. 16. 44. 26. 28. 35. 14. 34. 45. 32. 48. 31. 27.  0.  1.
 49. 29. 10.  7. 21. 62. 15. 43. 47.  2. 20. 23. 30. 17. 55.  4. 19. 56.
 nan 25. 38. 36. 22. 18. 42. 37. 13.  8. 40.  3. 54.  9.  6. 64. 67. 61.
 50. 41. 57. 11. 52. 51. 46. 60. 63. 59.  5. 79. 68. 74. 12. 53. 65. 71.
 75. 70. 76. 78. 73. 66. 69. 72. 77.]
VIP [False True nan]
RoomService [   0.  109.   43. ... 1569. 8586.  745.]
FoodCourt [   0.    9. 3576. ... 3208. 6819. 4688.]
ShoppingMall [   0.   25.  371. ... 1085.  510. 1872.]
Spa [   0.  549. 6715. ... 2868. 1107. 1643.]
VRDeck [   0.   44.   49. ... 1164.  971. 3235.]
Name ['Maham Ofracculy' 'Juanna Vines' 'Altark Susent' ... 'Fayey Connon'
 'Celeon Hontichre' 'Propsh Hontichre']
Transported [False  True]

In [3]:
df_train.drop(['PassengerId', 'Name', 'Cabin', 'HomePlanet', 'Destination'], axis=1, inplace=True)
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CryoSleep     8476 non-null   object
 1   Age           8514 non-null   float64
 2   VIP           8490 non-null   object
 3   RoomService   8512 non-null   float64
 4   FoodCourt     8510 non-null   float64
 5   ShoppingMall  8485 non-null   float64
 6   Spa           8510 non-null   float64
 7   VRDeck        8505 non-null   float64
 8   Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2)
memory usage: 551.9+ KB

In [4]:
df_train['VIP'] = df_train['VIP'].map(
    lambda x: 1 if x == 'Yes' else 0
)
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].mean())
df_train['RoomService'] = df_train['RoomService'].fillna(df_train['RoomService'].mean())
df_train['FoodCourt'] = df_train['FoodCourt'].fillna(df_train['FoodCourt'].mean())
df_train['ShoppingMall'] = df_train['ShoppingMall'].fillna(df_train['ShoppingMall'].mean())
df_train['Spa'] = df_train['Spa'].fillna(df_train['Spa'].mean())
df_train['VRDeck'] = df_train['VRDeck'].fillna(df_train['VRDeck'].mean())

df_train['Age'] = (df_train['Age'] - df_train['Age'].mean()) / df_train['Age'].std()
df_train['RoomService'] = (df_train['RoomService'] - df_train['RoomService'].mean()) / df_train['RoomService'].std()
df_train['FoodCourt'] = (df_train['FoodCourt'] - df_train['FoodCourt'].mean()) / df_train['FoodCourt'].std()
df_train['ShoppingMall'] = (df_train['ShoppingMall'] - df_train['ShoppingMall'].mean()) / df_train['ShoppingMall'].std()
df_train['Spa'] = (df_train['Spa'] - df_train['Spa'].mean()) / df_train['Spa'].std()
df_train['VRDeck'] = (df_train['VRDeck'] - df_train['VRDeck'].mean()) / df_train['VRDeck'].std()
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CryoSleep     8476 non-null   object
 1   Age           8693 non-null   float64
 2   VIP           8693 non-null   int64
 3   RoomService   8693 non-null   float64
 4   FoodCourt     8693 non-null   float64
 5   ShoppingMall  8693 non-null   float64
 6   Spa           8693 non-null   float64
 7   VRDeck        8693 non-null   float64
 8   Transported   8693 non-null   bool
dtypes: bool(1), float64(6), int64(1), object(1)
memory usage: 551.9+ KB

In [5]:
df_train['CryoSleep'] = df_train['CryoSleep'].map(
    lambda x: 1 if x == True else 0
)
df_train.to_csv('train_clean.csv', index=False)

df_test = pd.read_csv('test.csv')
df_test.drop(['Name', 'Cabin', 'HomePlanet', 'Destination'], axis=1, inplace=True)
df_test['VIP'] = df_test['VIP'].map(
    lambda x: 1 if x == 'Yes' else 0
)
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].mean())
df_test['RoomService'] = df_test['RoomService'].fillna(df_test['RoomService'].mean())
df_test['FoodCourt'] = df_test['FoodCourt'].fillna(df_test['FoodCourt'].mean())
df_test['ShoppingMall'] = df_test['ShoppingMall'].fillna(df_test['ShoppingMall'].mean())
df_test['Spa'] = df_test['Spa'].fillna(df_test['Spa'].mean())
df_test['VRDeck'] = df_test['VRDeck'].fillna(df_test['VRDeck'].mean())
df_test['CryoSleep'] = df_test['CryoSleep'].map(
    lambda x: 1 if x == True else 0
)

df_test['Age'] = (df_test['Age'] - df_test['Age'].mean()) / df_test['Age'].std()
df_test['RoomService'] = (df_test['RoomService'] - df_test['RoomService'].mean()) / df_test['RoomService'].std()
df_test['FoodCourt'] = (df_test['FoodCourt'] - df_test['FoodCourt'].mean()) / df_test['FoodCourt'].std()
df_test['ShoppingMall'] = (df_test['ShoppingMall'] - df_test['ShoppingMall'].mean()) / df_test['ShoppingMall'].std()
df_test['Spa'] = (df_test['Spa'] - df_test['Spa'].mean()) / df_test['Spa'].std()
df_test['VRDeck'] = (df_test['VRDeck'] - df_test['VRDeck'].mean()) / df_test['VRDeck'].std()
df_test.info()
df_test.to_csv('test_clean.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   CryoSleep     4277 non-null   int64
 2   Age           4277 non-null   float64
 3   VIP           4277 non-null   int64
 4   RoomService   4277 non-null   float64
 5   FoodCourt     4277 non-null   float64
 6   ShoppingMall  4277 non-null   float64
 7   Spa           4277 non-null   float64
 8   VRDeck        4277 non-null   float64
dtypes: float64(6), int64(2), object(1)
memory usage: 300.9+ KB